service: taxa-fixa-api

provider:
  name: aws
  runtime: python3.12  # Keeping this for reference
  region: eu-west-1
  ecr:
    images:
      appimage:
        uri: 238362649227.dkr.ecr.eu-west-1.amazonaws.com/serverless-taxa-fixa-api-dev:latest
functions:
  app:
    image:
      name: appimage  # Referencing the Docker image
    events:
      - httpApi: '*'  # Catch-all route for HTTP API

package:
  exclude:
    - venv/**